### ISSUE TITLE
Implementing backend services correctly

### ISSUE THREAD

**Issue by kotn3l** [kotn3l/OnlinePizzeria_Labor2#13]
Current backend service implementations (only PizzaService though) could use some more transparency, and the use of the recommended service template. (Core, Controller, DAO, Service, Web) Future services must be implemented using this scheme.

**Comment by kotn3l** [comment]
Oops, forgot to mention the issue in these two commits:
9feaeb0ea9778c256610405723823d03c61da240
65d8163b21743f52b84e899e096f5bcab5eda8d1

**Comment by kotn3l** [comment]
@lehorichard please check if the code works

**Comment by lehorichard** [comment]
@kotn3l It works fine. Backend authentication is coming soon<sup>TM</sup>
