### ISSUE TITLE
Backend Delivery services implementation

### ISSUE THREAD

**Issue by kotn3l** [kotn3l/OnlinePizzeria_Labor2#16]
- [x] **Delivery services**

- [x] Get all delivery guys
- [x] Post a delivery
- [x] Get deliveries by delivery guy
- [x] Post delivery done

- [x] **session string**

**Comment by kotn3l** [comment]
eefa914e9859864b5b33bcff94efe913d02d2654

**Comment by lehorichard** [comment]
a310407
