### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by PalKriah** [kotn3l/OnlinePizzeria_Labor2#7]
- [✓] Pizza service
- [✓] Order service
- [✓] Scheduling service
- [✓] Delivery service
- [✓] Authentication service
- [] Review

**Comment by lehorichard** [comment]
Ezeket akkor Draw.io-val kellene megcsinálni vagy van valami komolyabb cucc hozzá?

Szerintem ezeket fel lehetne osztani úgy, hogy mindenki megcsinál 1-2 servicet.

**Comment by PalKriah** [comment]
Már majdnem kész vannak, még az autentikációt kell kitalálni, szerintem azt holnap csinálom meg.

Én postman-nal csinálom, ha beregisztrálsz és elküldöd a regisztrált email címed akkor hozzáadlak és megnézheted mi van kész eddig.

**Comment by lehorichard** [comment]
Ja, akkor már mind. Majd a készeket megnézem.
